services:
  proton:
    image: ghcr.io/timeplus-io/proton:latest
    pull_policy: always
    ports:
      - 8463:8463
      - 3218:3218
  hn_stream:
    build:
      context: .  
    image: timeplus/hackernews_bytewax:latest
    environment:
      - PROTON_HOST=proton
    depends_on:
      - proton